// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "dartjni.h"
#include "jni.h"

thread_local JNIEnv* jniEnv;
JniContext* jni;

JniContext* (*context_getter)(void);
JNIEnv* (*env_getter)(void);

void setJniGetters(JniContext* (*cg)(void), JNIEnv* (*eg)(void)) {
  context_getter = cg;
  env_getter = eg;
}

// uk.ac.ox.eng.stepcounter.DataPoint
jclass _c_DataPoint = NULL;

jmethodID _m_DataPoint__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__new0(int64_t time, float magnitude) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__new0, "<init>", "(JF)V");
  if (_m_DataPoint__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_DataPoint,
                                         _m_DataPoint__new0, time, magnitude);
  return to_global_ref_result(_result);
}

jmethodID _m_DataPoint__new1 = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__new1(float time, float magnitude) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__new1, "<init>", "(FF)V");
  if (_m_DataPoint__new1 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_DataPoint,
                                         _m_DataPoint__new1, time, magnitude);
  return to_global_ref_result(_result);
}

jmethodID _m_DataPoint__setEos = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__setEos(jobject self_, uint8_t val) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__setEos, "setEos", "(Z)V");
  if (_m_DataPoint__setEos == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_DataPoint__setEos, val);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_DataPoint__getEos = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__getEos(jobject self_) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__getEos, "getEos", "()Z");
  if (_m_DataPoint__getEos == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  uint8_t _result =
      (*jniEnv)->CallBooleanMethod(jniEnv, self_, _m_DataPoint__getEos);
  return (JniResult){.value = {.z = _result}, .exception = check_exception()};
}

jmethodID _m_DataPoint__getMagnitude = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__getMagnitude(jobject self_) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__getMagnitude, "getMagnitude", "()F");
  if (_m_DataPoint__getMagnitude == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  float _result =
      (*jniEnv)->CallFloatMethod(jniEnv, self_, _m_DataPoint__getMagnitude);
  return (JniResult){.value = {.f = _result}, .exception = check_exception()};
}

jmethodID _m_DataPoint__setMagnitude = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__setMagnitude(jobject self_, float magnitude) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__setMagnitude, "setMagnitude",
              "(F)V");
  if (_m_DataPoint__setMagnitude == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_DataPoint__setMagnitude,
                            magnitude);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_DataPoint__getTime = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__getTime(jobject self_) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__getTime, "getTime", "()F");
  if (_m_DataPoint__getTime == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  float _result =
      (*jniEnv)->CallFloatMethod(jniEnv, self_, _m_DataPoint__getTime);
  return (JniResult){.value = {.f = _result}, .exception = check_exception()};
}

jmethodID _m_DataPoint__setTime = NULL;
FFI_PLUGIN_EXPORT
JniResult DataPoint__setTime(jobject self_, float time) {
  load_env();
  load_class_global_ref(&_c_DataPoint, "uk/ac/ox/eng/stepcounter/DataPoint");
  if (_c_DataPoint == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DataPoint, &_m_DataPoint__setTime, "setTime", "(F)V");
  if (_m_DataPoint__setTime == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_DataPoint__setTime, time);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.DetectionStage
jclass _c_DetectionStage = NULL;

jmethodID _m_DetectionStage__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult DetectionStage__new0(jobject input, jobject output) {
  load_env();
  load_class_global_ref(&_c_DetectionStage,
                        "uk/ac/ox/eng/stepcounter/DetectionStage");
  if (_c_DetectionStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DetectionStage, &_m_DetectionStage__new0, "<init>",
              "(Ljava/util/List;Ljava/util/List;)V");
  if (_m_DetectionStage__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(
      jniEnv, _c_DetectionStage, _m_DetectionStage__new0, input, output);
  return to_global_ref_result(_result);
}

jmethodID _m_DetectionStage__run = NULL;
FFI_PLUGIN_EXPORT
JniResult DetectionStage__run(jobject self_) {
  load_env();
  load_class_global_ref(&_c_DetectionStage,
                        "uk/ac/ox/eng/stepcounter/DetectionStage");
  if (_c_DetectionStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_DetectionStage, &_m_DetectionStage__run, "run", "()V");
  if (_m_DetectionStage__run == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_DetectionStage__run);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.FilterStage
jclass _c_FilterStage = NULL;

jmethodID _m_FilterStage__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult FilterStage__new0(jobject input, jobject output) {
  load_env();
  load_class_global_ref(&_c_FilterStage,
                        "uk/ac/ox/eng/stepcounter/FilterStage");
  if (_c_FilterStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_FilterStage, &_m_FilterStage__new0, "<init>",
              "(Ljava/util/List;Ljava/util/List;)V");
  if (_m_FilterStage__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_FilterStage,
                                         _m_FilterStage__new0, input, output);
  return to_global_ref_result(_result);
}

jmethodID _m_FilterStage__run = NULL;
FFI_PLUGIN_EXPORT
JniResult FilterStage__run(jobject self_) {
  load_env();
  load_class_global_ref(&_c_FilterStage,
                        "uk/ac/ox/eng/stepcounter/FilterStage");
  if (_c_FilterStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_FilterStage, &_m_FilterStage__run, "run", "()V");
  if (_m_FilterStage__run == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_FilterStage__run);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.PostProcessStage
jclass _c_PostProcessStage = NULL;

jmethodID _m_PostProcessStage__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult PostProcessStage__new0(jobject input,
                                 jobject newStepCallback,
                                 jobject endOfDataCallback) {
  load_env();
  load_class_global_ref(&_c_PostProcessStage,
                        "uk/ac/ox/eng/stepcounter/PostProcessStage");
  if (_c_PostProcessStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_PostProcessStage, &_m_PostProcessStage__new0, "<init>",
              "(Ljava/util/List;Luk/ac/ox/eng/stepcounter/"
              "PostProcessStage$OnNewStepDetected;Luk/ac/ox/eng/stepcounter/"
              "PostProcessStage$OnEndOfData;)V");
  if (_m_PostProcessStage__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_PostProcessStage,
                                         _m_PostProcessStage__new0, input,
                                         newStepCallback, endOfDataCallback);
  return to_global_ref_result(_result);
}

jmethodID _m_PostProcessStage__run = NULL;
FFI_PLUGIN_EXPORT
JniResult PostProcessStage__run(jobject self_) {
  load_env();
  load_class_global_ref(&_c_PostProcessStage,
                        "uk/ac/ox/eng/stepcounter/PostProcessStage");
  if (_c_PostProcessStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_PostProcessStage, &_m_PostProcessStage__run, "run", "()V");
  if (_m_PostProcessStage__run == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_PostProcessStage__run);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.PostProcessStage$OnEndOfData
jclass _c_PostProcessStage_OnEndOfData = NULL;

jmethodID _m_PostProcessStage_OnEndOfData__EodCallback = NULL;
FFI_PLUGIN_EXPORT
JniResult PostProcessStage_OnEndOfData__EodCallback(jobject self_) {
  load_env();
  load_class_global_ref(
      &_c_PostProcessStage_OnEndOfData,
      "uk/ac/ox/eng/stepcounter/PostProcessStage$OnEndOfData");
  if (_c_PostProcessStage_OnEndOfData == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_PostProcessStage_OnEndOfData,
              &_m_PostProcessStage_OnEndOfData__EodCallback, "EodCallback",
              "()V");
  if (_m_PostProcessStage_OnEndOfData__EodCallback == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_,
                            _m_PostProcessStage_OnEndOfData__EodCallback);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.PostProcessStage$OnNewStepDetected
jclass _c_PostProcessStage_OnNewStepDetected = NULL;

jmethodID _m_PostProcessStage_OnNewStepDetected__incrementSteps = NULL;
FFI_PLUGIN_EXPORT
JniResult PostProcessStage_OnNewStepDetected__incrementSteps(jobject self_) {
  load_env();
  load_class_global_ref(
      &_c_PostProcessStage_OnNewStepDetected,
      "uk/ac/ox/eng/stepcounter/PostProcessStage$OnNewStepDetected");
  if (_c_PostProcessStage_OnNewStepDetected == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_PostProcessStage_OnNewStepDetected,
              &_m_PostProcessStage_OnNewStepDetected__incrementSteps,
              "incrementSteps", "()V");
  if (_m_PostProcessStage_OnNewStepDetected__incrementSteps == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(
      jniEnv, self_, _m_PostProcessStage_OnNewStepDetected__incrementSteps);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.PreProcessStage
jclass _c_PreProcessStage = NULL;

jmethodID _m_PreProcessStage__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult PreProcessStage__new0(jobject input, jobject output) {
  load_env();
  load_class_global_ref(&_c_PreProcessStage,
                        "uk/ac/ox/eng/stepcounter/PreProcessStage");
  if (_c_PreProcessStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_PreProcessStage, &_m_PreProcessStage__new0, "<init>",
              "(Ljava/util/List;Ljava/util/List;)V");
  if (_m_PreProcessStage__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(
      jniEnv, _c_PreProcessStage, _m_PreProcessStage__new0, input, output);
  return to_global_ref_result(_result);
}

jmethodID _m_PreProcessStage__run = NULL;
FFI_PLUGIN_EXPORT
JniResult PreProcessStage__run(jobject self_) {
  load_env();
  load_class_global_ref(&_c_PreProcessStage,
                        "uk/ac/ox/eng/stepcounter/PreProcessStage");
  if (_c_PreProcessStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_PreProcessStage, &_m_PreProcessStage__run, "run", "()V");
  if (_m_PreProcessStage__run == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_PreProcessStage__run);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.ScoringStage
jclass _c_ScoringStage = NULL;

jmethodID _m_ScoringStage__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult ScoringStage__new0(jobject input, jobject output) {
  load_env();
  load_class_global_ref(&_c_ScoringStage,
                        "uk/ac/ox/eng/stepcounter/ScoringStage");
  if (_c_ScoringStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_ScoringStage, &_m_ScoringStage__new0, "<init>",
              "(Ljava/util/List;Ljava/util/List;)V");
  if (_m_ScoringStage__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_ScoringStage,
                                         _m_ScoringStage__new0, input, output);
  return to_global_ref_result(_result);
}

jmethodID _m_ScoringStage__run = NULL;
FFI_PLUGIN_EXPORT
JniResult ScoringStage__run(jobject self_) {
  load_env();
  load_class_global_ref(&_c_ScoringStage,
                        "uk/ac/ox/eng/stepcounter/ScoringStage");
  if (_c_ScoringStage == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_ScoringStage, &_m_ScoringStage__run, "run", "()V");
  if (_m_ScoringStage__run == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_ScoringStage__run);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.StepCounter
jclass _c_StepCounter = NULL;

jmethodID _m_StepCounter__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__new0(float samplingFreq) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__new0, "<init>", "(F)V");
  if (_m_StepCounter__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_StepCounter,
                                         _m_StepCounter__new0, samplingFreq);
  return to_global_ref_result(_result);
}

jmethodID _m_StepCounter__start = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__start(jobject self_) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__start, "start", "()V");
  if (_m_StepCounter__start == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_StepCounter__start);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_StepCounter__stop = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__stop(jobject self_) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__stop, "stop", "()V");
  if (_m_StepCounter__stop == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_StepCounter__stop);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_StepCounter__addOnStepUpdateListener = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__addOnStepUpdateListener(jobject self_,
                                               jobject listener) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__addOnStepUpdateListener,
              "addOnStepUpdateListener",
              "(Luk/ac/ox/eng/stepcounter/StepCounter$OnStepUpdateListener;)V");
  if (_m_StepCounter__addOnStepUpdateListener == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_,
                            _m_StepCounter__addOnStepUpdateListener, listener);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_StepCounter__setOnFinishedProcessingListener = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__setOnFinishedProcessingListener(jobject self_,
                                                       jobject listener) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(
      _c_StepCounter, &_m_StepCounter__setOnFinishedProcessingListener,
      "setOnFinishedProcessingListener",
      "(Luk/ac/ox/eng/stepcounter/StepCounter$OnFinishedProcessingListener;)V");
  if (_m_StepCounter__setOnFinishedProcessingListener == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(
      jniEnv, self_, _m_StepCounter__setOnFinishedProcessingListener, listener);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_StepCounter__incSteps = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__incSteps(jobject self_) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__incSteps, "incSteps", "()V");
  if (_m_StepCounter__incSteps == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_StepCounter__incSteps);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_StepCounter__processSample = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__processSample(jobject self_,
                                     int64_t time,
                                     jobject sample) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__processSample, "processSample",
              "(J[F)V");
  if (_m_StepCounter__processSample == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_StepCounter__processSample, time,
                            sample);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

jmethodID _m_StepCounter__getSteps = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__getSteps(jobject self_) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__getSteps, "getSteps", "()I");
  if (_m_StepCounter__getSteps == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  int32_t _result =
      (*jniEnv)->CallIntMethod(jniEnv, self_, _m_StepCounter__getSteps);
  return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

jmethodID _m_StepCounter__getSamplingFreq = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__getSamplingFreq(jobject self_) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__getSamplingFreq,
              "getSamplingFreq", "()F");
  if (_m_StepCounter__getSamplingFreq == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  float _result = (*jniEnv)->CallFloatMethod(jniEnv, self_,
                                             _m_StepCounter__getSamplingFreq);
  return (JniResult){.value = {.f = _result}, .exception = check_exception()};
}

jmethodID _m_StepCounter__setSamplingFreq = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter__setSamplingFreq(jobject self_, float samplingFreq) {
  load_env();
  load_class_global_ref(&_c_StepCounter,
                        "uk/ac/ox/eng/stepcounter/StepCounter");
  if (_c_StepCounter == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter, &_m_StepCounter__setSamplingFreq,
              "setSamplingFreq", "(F)V");
  if (_m_StepCounter__setSamplingFreq == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(jniEnv, self_, _m_StepCounter__setSamplingFreq,
                            samplingFreq);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.StepCounter$OnFinishedProcessingListener
jclass _c_StepCounter_OnFinishedProcessingListener = NULL;

jmethodID _m_StepCounter_OnFinishedProcessingListener__onFinishedProcessing =
    NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter_OnFinishedProcessingListener__onFinishedProcessing(
    jobject self_) {
  load_env();
  load_class_global_ref(
      &_c_StepCounter_OnFinishedProcessingListener,
      "uk/ac/ox/eng/stepcounter/StepCounter$OnFinishedProcessingListener");
  if (_c_StepCounter_OnFinishedProcessingListener == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(
      _c_StepCounter_OnFinishedProcessingListener,
      &_m_StepCounter_OnFinishedProcessingListener__onFinishedProcessing,
      "onFinishedProcessing", "()V");
  if (_m_StepCounter_OnFinishedProcessingListener__onFinishedProcessing == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(
      jniEnv, self_,
      _m_StepCounter_OnFinishedProcessingListener__onFinishedProcessing);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}

// uk.ac.ox.eng.stepcounter.StepCounter$OnStepUpdateListener
jclass _c_StepCounter_OnStepUpdateListener = NULL;

jmethodID _m_StepCounter_OnStepUpdateListener__onStepUpdate = NULL;
FFI_PLUGIN_EXPORT
JniResult StepCounter_OnStepUpdateListener__onStepUpdate(jobject self_,
                                                         int32_t steps) {
  load_env();
  load_class_global_ref(
      &_c_StepCounter_OnStepUpdateListener,
      "uk/ac/ox/eng/stepcounter/StepCounter$OnStepUpdateListener");
  if (_c_StepCounter_OnStepUpdateListener == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_StepCounter_OnStepUpdateListener,
              &_m_StepCounter_OnStepUpdateListener__onStepUpdate,
              "onStepUpdate", "(I)V");
  if (_m_StepCounter_OnStepUpdateListener__onStepUpdate == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  (*jniEnv)->CallVoidMethod(
      jniEnv, self_, _m_StepCounter_OnStepUpdateListener__onStepUpdate, steps);
  return (JniResult){.value = {.j = 0}, .exception = check_exception()};
}
